server:
  port: 8080
  tomcat:
    threads:
      max: 200
  servlet:
    context-path: /api/v1

spring:
  datasource:
    url: ${DBMS_URL:jdbc:mysql://localhost:3306/cake_shop}
    username: ${DBMS_USERNAME:root}
    password: ${DBMS_PASSWORD:root}
    driverClassName: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
      idle-timeout: 30000
      connection-timeout: 30000
      max-lifetime: 600000
      pool-name: HikariCP

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signerKey: "c4lhb8ZldnyryrCfPkkbhXr0aLNUYa9wyiGv9ntbApggtV3Iwy1E3KAPq+0cPugf"
  valid-duration: 600
  refreshable-duration: 3600

outbound:
  identity:
    client-id: "627966361130-8t8ee0l2obeenvgg9470lgp8sqn5vva7.apps.googleusercontent.com"
    client-secret: "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"
    redirect-uri: "http://localhost:8080/api/v1/oauth2/login/google/callback"